/**
 * Meme Answer Madness
 * The API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlayerDto } from './player-dto';
import { RoundDto } from './round-dto';


export interface RoomDto { 
    id: string;
    name: string;
    rounds: Array<RoundDto>;
    players?: Array<PlayerDto>;
    numberOfRounds: number;
    status: string;
}

