/**
 * Meme Answer Madness
 * The API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnswerDto } from './answer-dto';


export interface RoundDto { 
    memeUrl: string;
    answers?: Array<AnswerDto>;
}

